// scripts/build-seed.js
// Builds the seed SQL for all 33 seasons of 나는 SOLO
// v2: Added ideal_type, catchphrase, hobbies, marital_history, is_final_couple,
//     final_choice, eliminated_episode, recent_news, data_source, confidence
// Uses subqueries for ALL foreign keys so the script works regardless of
// any pre-existing rows / auto-id offsets in the database.
//
// Run with: node scripts/build-seed.js

const fs = require("fs");
const path = require("path");

const PORTRAIT_COLORS = ["rose", "gold", "navy", "sage", "plum"];

// Schema-allowed value mappings
const STATUS_MAP = {
  engaged: "dating",
  in_relationship: "dating",
  withdrew: "unknown",
};
function normalizeStatus(s) {
  if (!s) return "unknown";
  return STATUS_MAP[s] || s;
}

const MARITAL_MAP = {
  never_married: "never_married",
  single_parent: "divorced", // legacy
  돌싱: "divorced",
  돌돌싱: "twice_divorced",
  사별: "widowed",
  사실혼: "de_facto",
  혼전임신: "de_facto",
};
function normalizeMarital(s) {
  if (!s) return "unknown";
  return MARITAL_MAP[s] || s;
}

function sqlEscape(s) {
  if (s == null) return "NULL";
  if (Array.isArray(s)) {
    if (s.length === 0) return "ARRAY[]::text[]";
    return `ARRAY[${s.map((x) => sqlEscape(String(x))).join(", ")}]`;
  }
  return `'${String(s).replace(/'/g, "''")}'`;
}

function dateFromYear(y) {
  if (!y) return "NULL";
  return `'${y}-01-01'::date`;
}

function colorFor(idx) {
  return PORTRAIT_COLORS[idx % PORTRAIT_COLORS.length];
}

// ----- Load data -----
const SEASONS = [];
const COUPLES = [];
for (const f of ["raw-1-8.json", "raw-9-17.json", "raw-18-25.json", "raw-26-33.json"]) {
  const data = JSON.parse(
    fs.readFileSync(path.join(__dirname, "..", "data", f), "utf8")
  );
  SEASONS.push(...data.seasons);
  if (data.couples) COUPLES.push(...data.couples);
}
SEASONS.sort((a, b) => a.season_number - b.season_number);

let out = "";

// ====== HEADER ======
out += `-- =========================================================================
-- 솔로위키 · Solo Wiki — Full seed: 1기 ~ 33기
-- Generated by scripts/build-seed.js (v2 — extended fields)
-- =========================================================================
-- 모든 출연자는 팬 큐레이션 정보(가명/직업/연령 등)이며 fan-curated dataset.
-- 모든 FK는 subquery로 매핑 → DB에 기존 row 있어도 안전.
-- 재생성: node scripts/build-seed.js
-- =========================================================================

-- ----- 1) seasons -----
insert into public.seasons (number, title, air_date_start, air_date_end, episode_count, description, is_published, sort_order)
values
`;

const seasonRows = SEASONS.map((s, i) => {
  const desc = s.location_filming
    ? `${s.title.replace(/^\d+기.*\(.*\)$/, "").trim() || s.title} — ${s.location_filming}`
    : null;
  return `  (${s.season_number}, ${sqlEscape(s.title)}, ${s.air_date_start ? sqlEscape(s.air_date_start) + "::date" : "NULL"}, ${s.air_date_end ? sqlEscape(s.air_date_end) + "::date" : "NULL"}, ${s.episode_count ?? "NULL"}, ${sqlEscape(desc)}, true, ${i})`;
});
out += seasonRows.join(",\n") + ";\n\n";

// ====== 2) contestants (v2 — all fields) ======
out += `-- ----- 2) contestants (${SEASONS.reduce((n, s) => n + s.contestants.length, 0)} rows, v2 schema) -----
-- season_id via subquery — season number 로 lookup
insert into public.contestants (
  season_id, name, name_initial, gender, birth_date, age_at_appearance,
  job, job_category, location_city, location_district,
  mbti, height_cm, body_type, education,
  intro, ideal_type, catchphrase, charm_points, hobbies,
  marital_history, current_status, is_final_couple, final_choice, eliminated_episode,
  partner_id,
  instagram_handle, instagram_followers, tiktok_handle, tiktok_followers, youtube_handle,
  recent_news, data_source, confidence,
  portrait_color, appearance_order, is_published
)
values
`;

const contestantRows = [];
for (const s of SEASONS) {
  s.contestants.forEach((c, idx) => {
    const portrait = c.portrait_color || colorFor(idx);
    const location = c.location_city || null;
    const insta = c.instagram_handle
      ? c.instagram_handle
          .replace(/^@/, "")
          .replace(/^https?:\/\/(www\.)?instagram\.com\//, "")
          .replace(/\/$/, "")
      : null;
    contestantRows.push(`  (
    (select id from public.seasons where number = ${s.season_number}),
    ${sqlEscape(c.gamyeong)},
    ${sqlEscape(c.gamyeong)},
    '${c.gender}',
    ${dateFromYear(c.birth_year)},
    ${c.age_at_appearance ?? "NULL"},
    ${sqlEscape(c.job)},
    ${sqlEscape(c.job_category)},
    ${sqlEscape(location)},
    NULL,
    ${sqlEscape(c.mbti ?? null)},
    ${c.height_cm ?? "NULL"},
    ${sqlEscape(c.body_type ?? null)},
    ${sqlEscape(c.education ?? null)},
    ${sqlEscape(c.intro ?? null)},
    ${sqlEscape(c.ideal_type ?? null)},
    ${sqlEscape(c.catchphrase ?? null)},
    ${sqlEscape(c.charm_points ?? null)},
    ${sqlEscape(c.hobbies ?? null)},
    '${normalizeMarital(c.marital_history)}',
    '${normalizeStatus(c.current_status)}',
    ${c.is_final_couple === true ? "true" : "false"},
    ${sqlEscape(c.final_choice ?? null)},
    ${c.eliminated_episode ?? "NULL"},
    NULL,
    ${insta ? sqlEscape(insta) : "NULL"},
    ${c.instagram_followers ?? "NULL"},
    ${sqlEscape(c.tiktok_handle ?? null)},
    ${c.tiktok_followers ?? "NULL"},
    ${sqlEscape(c.youtube_handle ?? null)},
    ${sqlEscape(c.recent_news ?? null)},
    ${sqlEscape(c.data_source ?? null)},
    '${c.confidence || "medium"}',
    '${portrait}',
    ${idx + 1},
    true
  )`);
  });
}
out += contestantRows.join(",\n") + ";\n\n";

// ====== 3) contestant_stats — default 50 each (v3 — 10 stats) ======
out += `-- ----- 3) contestant_stats (v3 — 10 stats, default 50) -----
-- contestant_id via (season_number, name) join
insert into public.contestant_stats (contestant_id, overall_charm, villain_power, appearance, inner_qualities, career_score, age_score, conversation, style_score, intelligence_score, appetite)
select c.id, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50
from public.contestants c
join public.seasons s on c.season_id = s.id
join (values
${SEASONS.flatMap((s) => s.contestants.map((c) => `  (${s.season_number}, ${sqlEscape(c.gamyeong)})`)).join(",\n")}
) as v(season_number, contestant_name) on s.number = v.season_number and c.name = v.contestant_name;
`;

// ====== 3.5) highlights — YouTube scenes per contestant ======
let highlightCount = 0;
let highlightRows = [];
for (const s of SEASONS) {
  s.contestants.forEach((c, idx) => {
    if (!c.highlights || !Array.isArray(c.highlights) || c.highlights.length === 0) return;
    c.highlights.forEach((h, hIdx) => {
      if (!h || !h.youtube_id) return;
      highlightRows.push(`  (
    (select c.id from public.contestants c
     join public.seasons s on c.season_id = s.id
     where s.number = ${s.season_number} and c.name = ${sqlEscape(c.gamyeong)}),
    ${sqlEscape(h.youtube_id)},
    ${sqlEscape(h.title ?? null)},
    ${sqlEscape(h.description ?? null)},
    ${h.duration_sec ?? "NULL"},
    ${sqlEscape(h.source_channel ?? "fan")},
    ${hIdx}
  )`);
      highlightCount++;
    });
  });
}

if (highlightRows.length > 0) {
  out = out.replace(
    /-- ----- 3\) contestant_stats/,
    `-- ----- 3) highlights (${highlightCount} YouTube scenes across all contestants) -----
insert into public.highlights (contestant_id, youtube_id, title, description, duration_sec, source_channel, sort_order)
values
${highlightRows.join(",\n")};

-- ----- 3.5) contestant_stats`
  );
}

// ====== 4) partner relationships ======
out += `
-- ----- 4) partner relationships (${COUPLES.length} couples) -----
-- partner_id via (season_number, name) subquery — cross-season safe
`;

let coupleCount = 0;
for (const c of COUPLES) {
  if (!c.m || !c.f) continue;
  const dateStr = c.date ? ` (${c.type}, ${c.date})` : ` (${c.type})`;
  out += `-- ${c.m.s}기 ${c.m.g} ↔ ${c.f.s}기 ${c.f.g}${dateStr}\n`;
  // m -> f
  out += `update public.contestants set partner_id = (
  select c2.id from public.contestants c2
  join public.seasons s2 on c2.season_id = s2.id
  where s2.number = ${c.f.s} and c2.name = ${sqlEscape(c.f.g)}
)
where id = (
  select c1.id from public.contestants c1
  join public.seasons s1 on c1.season_id = s1.id
  where s1.number = ${c.m.s} and c1.name = ${sqlEscape(c.m.g)}
);
`;
  // f -> m
  out += `update public.contestants set partner_id = (
  select c2.id from public.contestants c2
  join public.seasons s2 on c2.season_id = s2.id
  where s2.number = ${c.m.s} and c2.name = ${sqlEscape(c.m.g)}
)
where id = (
  select c1.id from public.contestants c1
  join public.seasons s1 on c1.season_id = s1.id
  where s1.number = ${c.f.s} and c1.name = ${sqlEscape(c.f.g)}
);
`;
  coupleCount++;
}

// ====== 5) sample community posts ======
out += `
-- ----- 5) Sample community posts (1기) -----
insert into public.posts (season_id, content, anonymous_name, vote_up_count)
values
  ((select id from public.seasons where number = 1),
   '영호 첫 등장 진짜 압도적이었음. 그때 운명이었나..',
   '달빛한입', 24),
  ((select id from public.seasons where number = 1),
   '영훈 강사 진짜 유머 끝판왕이네 ㅋㅋㅋ 다시 봐도 신선함',
   '솔로관찰자', 18),
  ((select id from public.seasons where number = 1),
   '영자 디자이너 손 그림 진짜 잘 그렸는데 그 장면 보고 빠졌음',
   '밤의독자', 31);
`;

const outPath = path.join(__dirname, "..", "supabase", "migrations", "0002_seed_all.sql");
fs.writeFileSync(outPath, out, "utf8");

console.log(`✅ Generated ${outPath}`);
console.log(`   - Seasons: ${SEASONS.length}`);
console.log(`   - Contestants: ${contestantRows.length}`);
console.log(`   - Highlights: ${highlightCount}`);
console.log(`   - Couples: ${coupleCount}`);
console.log(`   - Size: ${(fs.statSync(outPath).size / 1024).toFixed(1)} KB`);
